/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Akademik;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Asus
 */
public class Mahasiswa extends javax.swing.JFrame {
public Connection conn;
public Statement cn;


    public Mahasiswa() {
        initComponents();
        bersih();
        jtxtnim.requestFocus();
        tampildata();
    }
    public void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/akademik","root","");
            cn = conn.createStatement();
    }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "gagal");
            System.out.println(e.getMessage());
        }
}
    public void bersih(){
        jtxtnim.setText("");
        jtxtsiswa.setText("");
        jcbjurusan.setSelectedItem("--pilih--");   
    }
    
    public void tampildata(){
        DefaultTableModel tabelnya = new DefaultTableModel();
        
        tabelnya.addColumn("nim");
        tabelnya.addColumn("nama");
        tabelnya.addColumn("jurusan");
        
        try{
            koneksi();
            String sql = "Select * from tabelmahasiswa order by nim asc";
            ResultSet rs = cn.executeQuery(sql);
            while (rs.next()){
                tabelnya.addRow (new Object[]{
                   rs.getString(1),
                   rs.getString(2), 
                   rs.getString(3), 
                });
            }
            jTable1.setModel(tabelnya);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "ada kesalahan");
        }
    }
    
    public void cari(){
        try{
            koneksi();
            String sql = "Select * from tabelmahasiswa where nim='" + jtxtnim.getText()+ "'";
            ResultSet rs = cn.executeQuery(sql);
            
            if(rs.next()){
                jtxtnim.setText(rs.getString(1));
                jtxtsiswa.setText(rs.getString(2));
                jcbjurusan.setSelectedItem(rs.getString(3));
                
                JOptionPane.showMessageDialog(null, "Data mahasiswa : " + jtxtnim.getText() + "sudah ada");
                bersih();
            }
        }catch (Exception e){
            jtxtnim.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bkeluar = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        jtxtsiswa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtnim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcbjurusan = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jtxtcari = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");
        jScrollPane2.setViewportView(jLabel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 177, -1, -1));

        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel1.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 121, 91, -1));

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 23, -1, -1));

        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        jPanel1.add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 71, 91, -1));
        jPanel1.add(jtxtsiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 95, 330, -1));

        jLabel3.setText("JURUSAN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 146, -1, -1));

        jtxtnim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtnimKeyPressed(evt);
            }
        });
        jPanel1.add(jtxtnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 47, 330, -1));

        jLabel2.setText("SISWA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 98, -1, -1));

        jLabel1.setText("NIM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jcbjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "RPL", "TKJ", "DKV" }));
        jPanel1.add(jcbjurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 148, 333, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 230));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jtxtcari.setBackground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "nim", "nama", "jurusan"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jtxtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jtxtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        try{
            koneksi();
            String sql = "Insert into tabelmahasiswa values ('" + jtxtnim.getText() +
            "' , '" + jtxtsiswa.getText() + "','" + jcbjurusan.getSelectedItem() + "')";

            cn.executeUpdate(sql);
            conn.close();

            tampildata();
            bersih();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "penyimpanan gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        try {
            String sql = "update tabelmahasiswa set nama='" + jtxtsiswa.getText() +"'," + "jurusan='" + jcbjurusan.getSelectedItem() + "'"
            + "where nim='" + jtxtnim.getText() + "'";

            cn.executeUpdate(sql);
            conn.close();

            tampildata();
            bersih();
            jtxtnim.setEnabled(true);
            jtxtnim.requestFocus();
            jtxtsiswa.setEnabled(true);
            jcbjurusan.setEnabled(true);

            JOptionPane.showMessageDialog(null, "data berhasil dirubah");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "perubahan gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        try{
            koneksi();
            String sql = "delete from tabelmahasiswa where nim='" + jtxtnim.getText() + "'";
            cn.executeUpdate(sql);
            conn.close();

            tampildata();
            bersih();
            jtxtnim.setEnabled(true);
            jtxtnim.requestFocus();
            jtxtsiswa.setEnabled(true);
            jcbjurusan.setEnabled(true);

            JOptionPane.showMessageDialog(null, "berhasil dihapus");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "perubahan gagal");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        int answer = JOptionPane.showConfirmDialog(null, "konfirmasi keluar?", "informasi", JOptionPane.YES_NO_OPTION);
        if (answer==JOptionPane.YES_NO_OPTION){
            dispose();
        }
        else{
            return;
        }
    }//GEN-LAST:event_bkeluarActionPerformed

    private void jtxtnimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnimKeyPressed
        if(evt.getKeyCode()==10){
            cari();
        }
    }//GEN-LAST:event_jtxtnimKeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int table = jTable1.getSelectedRow();
        
        String a = jTable1.getValueAt(table, 0).toString();
        String b = jTable1.getValueAt(table, 1).toString();
        String c = jTable1.getValueAt(table, 2).toString();
        
        jtxtnim.setText(a);
        jtxtsiswa.setText(b);
        jcbjurusan.setSelectedItem(c);
        
        jtxtnim.setEnabled(false);
        jtxtsiswa.requestFocus();
        jcbjurusan.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbjurusan;
    private javax.swing.JTextField jtxtcari;
    private javax.swing.JTextField jtxtnim;
    private javax.swing.JTextField jtxtsiswa;
    // End of variables declaration//GEN-END:variables
}
